#pragma config(Sensor, S1,     leftLight,      sensorEV3_Color)
#pragma config(Sensor, S2,     rightLight,     sensorEV3_Color)
#pragma config(Sensor, S3,     mr_touch,       sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void lineFollow(int lightThresh){
	if (SensorValue(leftLight) < lightThresh){
		motor[motorA] = -20;
		motor[motorB] = 0;
	}
	else if (SensorValue(leftLight) > lightThresh) {
		motor[motorB] = -20;
		motor[motorA] = 0;
	}
}
void resetEncoders(){
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorB] = 0;
}
float distance(){
	float circum = 5.6 * 3.14159;
	float degdist = circum/360;
	float distance = degdist*((nMotorEncoder[motorB]+nMotorEncoder[motorA])/2);
	return distance;
}
void numbleftturns(int turns){
	while(turns>0){
		nMotorEncoder[motorB] = 0;
		while(nMotorEncoder[motorB]>-176){                   //turn left 90 degrees
			motor[motorB]=-25;
			motor[motorC]=25;
		}
		motor[motorB]=0;
		motor[motorC]=0;
		wait1Msec(250);
		turns--;
	}
}
void numbrightturns(int turn){ // turning right
	while(turn>0){
		nMotorEncoder[motorB] = 0;
		while(nMotorEncoder[motorB]<176){
			motor[motorB]=25;
			motor[motorC]=-25;
		}
		motor[motorB]=0;
		motor[motorC]=0;
		turn--;
	}
}
void alignment(){
	int lightThresh = 40;
		//orientation against a line (not too angled)
	while((SensorValue(leftLight)>lightThresh) && (SensorValue(rightLight)>lightThresh)){
		nMotorEncoder[motorB]=0;
		while(nMotorEncoder[motorB]<30){
			motor[motorB] = 25;
			motor[motorC] = 0;
		}
		nMotorEncoder[motorC]=0;
		while(nMotorEncoder[motorC]<30){
			motor[motorB] = 0;
			motor[motorC] = 25;
		}
	}
	if(SensorValue(leftLight)<lightThresh){
		while(SensorValue(rightLight)>lightThresh){
			motor[motorB] = 0;
			motor[motorC] = 25;
		}
	}
	else{
		while(SensorValue(leftLight)>lightThresh){
			motor[motorB] = 25;
			motor[motorC] = 0;
		}
	}
}
task main()
{
	resetEncoders();
	while(SensorValue(mr_touch) == 0){
		lineFollow(20);
	}
	float returneddistance = distance();
	displayTextLine(3, "distance:%f", returneddistance);
	wait1Msec(5000);
}
