#pragma config(Sensor, S1,     leftLight,      sensorEV3_Color)
#pragma config(Sensor, S2,     rightLight,     sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int lightbase = 20;
while (1==1) {
	if(SensorValue(leftLight) > lightbase) {
		motor[motorA] = 25;
		motor[motorB] = 0;
	}
	else if(SensorValue(leftLight) < lightbase) {
		motor[motorA] = 25;
		motor[motorB] = 25;
	}
	else if(SensorValue(rightLight) < lightbase) {
		motor[motorA] = 0;
		motor[motorB] = 25;
	}
	else if(SensorValue(rightLight) > lightbase) {
		motor[motorA] = 25;
		motor[motorB] = 25;
	}
}


}
