#pragma config(Sensor, S4,     ultrasound,     sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


int distance;
distance = 15;
int distanceThresh = 35;


while(SensorValue(ultrasound)>distanceThresh) {
	motor[motorA] = 35;
	motor[motorB] = 0;
}
}
